{% set name = "deepchecks" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deepchecks-{{ version }}.tar.gz
  sha256: 7bf419bcdf01ff282680720b5d4d71416c72acbfa055a948d004544cd067c0f6

build:
  skip: true  # [py>311]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pandas >=1.1.5,<2.2.0
    - numpy >=1.22.2
    - scikit-learn >=0.23.2,<1.4.0
    - jsonpickle >=2
    - pynomaly >=0.3.3

    # require for python 3.8+
    - ipython >=7.15.0  # [py>=38]
    - ipykernel >=5.3.0  # [py>=38]
    - ipywidgets >=7.6.5  # [py>=38]

    - typing-extensions >=4.0.0
    - tqdm >=4.62.3
    - category_encoders >=2.3.0

    - importlib_resources >=1.3  # [py<39]
    - importlib-metadata >=1.4

    # Category encoder depends on old statsmodels version which raises pandas warning. until dependency in category-encoders
    # is updated, explicitly add it here
    - statsmodels >=0.13.5

    - scipy >=1.4.1,<=1.10.1
    - plotly >=5.13.1
    - matplotlib-base >=3.3.4
    - beautifulsoup4 >=4.11.1
    - requests >=2.22.0
    - jupyter_server >=2.7.2

test:
  imports:
    - deepchecks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepchecks/deepchecks
  summary: Test Suites for Validating ML Models & Data
  doc_url: https://docs.deepchecks.com/
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
