{% set name = "deepchecks" %}
{% set version = "0.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deepchecks-{{ version }}.tar.gz
  sha256: 12d5602cc404c81050a47b5135b66c33322dd752f8e6cad4558add049292e763

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools <82
  run:
    - python >={{ python_min }}
    - pandas >=1.1.5
    - numpy >=1.22.2
    - scikit-learn >=0.23.2
    - jsonpickle >=2
    - pynomaly >=0.3.3
    - ipython >=7.15.0
    - ipykernel >=5.3.0
    - ipywidgets >=7.6.5
    - typing-extensions >=4.0.0
    - tqdm >=4.62.3
    - category_encoders >=2.3.0
    - statsmodels >=0.13.5
    - scipy >=1.4.1
    - plotly >=5.13.1
    - matplotlib-base >=3.3.4
    - beautifulsoup4 >=4.11.1
    - requests >=2.22.0
    - jupyter_server >=2.7.2

    # accomodate pkg_resources
    - setuptools <82

test:
  imports:
    - deepchecks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepchecks/deepchecks
  summary: Test Suites for Validating ML Models & Data
  doc_url: https://docs.deepchecks.com/
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
