{% set name = "deepchecks" %}
{% set version = "0.17.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepchecks-{{ version }}.tar.gz
  sha256: f1673ac47e64430f74efed8745be16cf5c1a9553374231fd9d9022561c4e6411

build:
  skip: True  # [py<36]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - beautifulsoup4 >=4.11.1
    - category_encoders >=2.3.0
    - dataclasses >=0.6  # [py<37]
    - importlib_resources >=1.3  # [py<39]
    - importlib_metadata >=1.4  # [py<38]
    - ipykernel >=5.3.0  # [py>=38]
    - ipykernel >=4.10.1  # [py<38]
    - ipython >=7.15.0,<8  # [py>=38]
    - ipython >=5.5.0,<8  # [py<38]
    - ipywidgets >=7.6.5,<8  # [py>=38]
    - ipywidgets >=7.5.0,<8  # [py<38]
    - jsonpickle >=2
    - matplotlib-base >=3.3.4
    - numpy >=1.19
    - pandas >=1.1.5
    - plotly >=5.13.1
    - pynomaly >=0.3.3
    - python
    - pyzmq <24.0.0
    - requests >=2.22.0
    - scikit-learn >=0.23.2
    - scipy >=1.4.1,<=1.10.1
    - statsmodels >=0.11.0  # [py<37]
    - statsmodels >=0.13.5  # [py>=37]
    - tqdm >=4.62.3
    - typing-extensions >=4.0.0

test:
  imports:
    - deepchecks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepchecks/deepchecks
  summary: Test Suites for Validating ML Models & Data
  doc_url: https://docs.deepchecks.com/
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
