{% set name = "deepchecks" %}
{% set version = "0.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepchecks-{{ version }}.tar.gz
  sha256: 0c05ba7d969ad6d5b1647562d533edc296d4665ed2a573be5cdb78788d2f6e00

build:
  skip: true  # [py<36 or py>310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

    # Adding upper constrain here as higher version pandas fails
    - pandas >=1.1.5,<=2.0.3
    - numpy >=1.19
    - scikit-learn >=0.23.2
    - jsonpickle >=2
    - pynomaly >=0.3.3

    # require for python 3.8+
    - ipython >=7.15.0,<8  # [py>=38]
    - ipykernel >=5.3.0  # [py>=38]
    - ipywidgets >=7.6.5,<8  # [py>=38]

    # google colab requirements (python 3.7)
    - ipython >=5.5.0,<8  # [py<38]
    - ipykernel >=4.10.1  # [py<38]
    - ipywidgets >=7.5.0,<8  # [py<38]

    - typing-extensions >=4.0.0
    - tqdm >=4.62.3
    - category_encoders >=2.3.0

    - importlib_resources >=1.3  # [py<39]  
    - importlib_metadata >=1.4  # [py<38]

    # Category encoder depends on old statsmodels version which raises pandas warning. until dependency in category-encoders
    # is updated, explicitly add it here
    - statsmodels >=0.11.0  # [py<37]
    - statsmodels >=0.13.5  # [py>=37]

    - scipy >=1.4.1,<=1.10.1
    - dataclasses >=0.6  # [py<37]
    - plotly >=5.13.1
    - matplotlib-base >=3.3.4
    - pyzmq <24.0.0
    - beautifulsoup4 >=4.11.1
    - requests >=2.22.0

test:
  imports:
    - deepchecks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepchecks/deepchecks
  summary: Test Suites for Validating ML Models & Data
  doc_url: https://docs.deepchecks.com/
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
