schema_version: 1

context:
  name: deepchecks
  version: "0.19.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/deepchecks-${{ version }}.tar.gz
  sha256: 12d5602cc404c81050a47b5135b66c33322dd752f8e6cad4558add049292e763

build:
  number: 4
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools <81
  run:
    - python >=${{ python_min }}
    - pandas >=1.1.5
    - numpy >=1.22.2
    # sklearn <1.6 needed to solve max_error deprecation
    - scikit-learn >=0.23.2,<1.6
    - jsonpickle >=2
    - pynomaly >=0.3.3
    - ipython >=7.15.0
    - ipykernel >=5.3.0
    - ipywidgets >=7.6.5
    - typing-extensions >=4.0.0
    - tqdm >=4.62.3
    - category_encoders >=2.3.0
    - statsmodels >=0.13.5
    - scipy >=1.4.1
    - plotly >=5.13.1
    - matplotlib-base >=3.3.4
    - beautifulsoup4 >=4.11.1
    - requests >=2.22.0
    - jupyter_server >=2.7.2
    # accomodate pkg_resources and supress warning use <81
    - setuptools <81

tests:
  - python:
      imports:
        - deepchecks
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Test Suites for Validating ML Models & Data
  license: AGPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/deepchecks/deepchecks
  documentation: https://docs.deepchecks.com/

extra:
  recipe-maintainers:
    - thewchan
